### ISSUE TITLE
Hello, is there any relevant paper description?

### ISSUE THREAD

**Issue by 670555467** [lasseufpa/rrm-slice-rl#1]

**Comment by cleversonahum** [comment]
I've submitted its paper and I am waiting for the journal review. I will update the repository as soon as I get it approved.

**Comment by cleversonahum** [comment]
Hello @670555467,  in case you are still interested. Our paper was published here https://ieeexplore.ieee.org/document/10205524

**Comment by 670555467** [comment]
> 您好，如果您仍然感兴趣。我们的论文发表在这里 https://ieeexplore.ieee.org/document/10205524

Hello, I am still interested in your work. May I ask if the code submitted now is complete?

> Hello @670555467, in case you are still interested. Our paper was published here https://ieeexplore.ieee.org/document/10205524

Hello, I am still interested in your work. May I ask if the code submitted now is complete?

**Comment by cleversonahum** [comment]
@670555467 Yes, it is.
