### ISSUE TITLE
can I know from where generate trial-ue inside sa folder ?

### ISSUE THREAD

**Issue by Karrar-Ibrahim** [lasseufpa/rrm-slice-rl#2]
Hi, can I know from where generate trial-ue inside sa folder ?
There are any csv data file ?

**Comment by cleversonahum** [comment]
Hello @Karrar-Ibrahim, we generated the spectral efficiency values for each UE using the [QuaDRiGa simulator](https://github.com/fraunhoferhhi/QuaDRiGa) with the code [here](https://github.com/Ryandry1st/QuaDRiGA-Simulation-Extensions). We've submitted the paper explaining our simulation and I should make it publicly available as soon as we get a response.

**Comment by cleversonahum** [comment]
@Karrar-Ibrahim just in case you still interested, our paper just got published here https://ieeexplore.ieee.org/document/10205524

**Comment by cleversonahum** [comment]
@Karrar-Ibrahim Just in case you are still interested, our paper was got published here https://ieeexplore.ieee.org/document/10205524
