### ISSUE TITLE
How to accelerate the training phase.

### ISSUE THREAD

**Issue by Linsooon** [lasseufpa/rrm-slice-rl#3]
Hello, Thanks for this nice works. I am wondering how to speed up the training phase. It takes quite a long time (a week for my device) for one run. 
or if it is possible to decrease some amount of the parameters (total_trails, steps_per_trails) and still has a decent result.
Thanks for advanced.

**Comment by cleversonahum** [comment]
Hi @Linsooon, are you running the hyperparameter optimization? In case yes, you can skip it. About the training phase, you can check the tensorboard logs to verify if the agent is performing satisfactorily before completing all the pre-specified episode numbers. You can use a Callback to perform this early stop automatically using SB3 as described [here](https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html). Another alternative is trying to migrate Stablebaselines3 to  [SBX](https://github.com/araffin/sbx) (stablebaselines using Jax).

**Comment by Linsooon** [comment]
I am running `run.py` only. thanks for your response. I will try those advices.
